### ISSUE TITLE
Certificate expired: paolo_at_codesake_dot_com.pem

### ISSUE THREAD

**Issue by gawin** [thesp0nge/dawnscanner#100]
Trying to install the paolo_at_codesake_dot_com.pem, but it looks to be expired.
Removed the old certificate and added the new one, but that also seems expired.

```bash
$ gem cert --list
/CN=paolo/DC=codesake/DC=com

$ gem cert --remove ''
Removed '/CN=paolo/DC=codesake/DC=com'

$ gem cert --list

$ gem cert --add <(curl -Ls https://raw.githubusercontent.com/thesp0nge/dawn/master/certs/paolo_at_codesake_dot_com.pem)
Added '/CN=paolo/DC=codesake/DC=com'

$ gem install dawnscanner -P MediumSecurity
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=paolo/DC=codesake/DC=com not valid after 2015-01-27 17:25:01 UTC
```

**Comment by thesp0nge** [comment]
Wow, this is huge.
I'll working on that.

Thanks
Paolo

**Comment by gawin** [comment]
Well, it's an easy fix, although I was a bit surprised that nobody reported it yet.

You probably already know this: Set reminders for certificate expiration dates, so you receive a notification to renew them before they expire.
I also wrote a small script that automatically finds certificates and checks the expiration dates for all the repositories and servers I manage.

Both saved me a lot of troubles of the years ;-)

Let me know if you need any help.

**Comment by thesp0nge** [comment]
Since nobody reported me, it means... no one installed the gem since Jan 27 and no reports :-(

Thanks

**Comment by thesp0nge** [comment]
New version 1.3.0 signed with the new key.
I close the issue, thanks again Gawin.

**Comment by gawin** [comment]
:+1:
