### ISSUE TITLE
Error when gem install dawnscanner -P MediumSecurity

### ISSUE THREAD

**Issue by igorescobar** [thesp0nge/dawnscanner#102]
❯❯❯ gem cert --add <(curl -Ls https://raw.githubusercontent.com/thesp0nge/dawnscanner/master/certs/paolo_at_dawnscanner_dot_org.pem)  
`Added '/CN=paolo/DC=dawnscanner/DC=org'`

❯❯❯  gem install dawnscanner -P MediumSecurity

```
Fetching: rainbow-2.0.0.gem (100%)
WARNING:  rainbow-2.0.0 is not signed
ERROR:  While executing gem ... (Gem::Security::Exception)
    missing signing certificate
```

Any ideas?

**Comment by kristian-hermansen** [comment]
I second this issue...

**Comment by thesp0nge** [comment]
Digital gem signing is a serious issue. I'm sad third party people doesn't sign their gem... I'm thinking on how to override this...

**Comment by thesp0nge** [comment]
Rainbow should be removed by dependencies now.

**Comment by funkyboy** [comment]
Getting this error now
```
> gem install dawnscanner -P LowSecurity
WARNING:  cvss-0.99.0 is not signed
ERROR:  While executing gem ... (Gem::Security::Exception)
    missing signing certificate
```

Same with `MediumSecurity`

**Comment by thesp0nge** [comment]
There's no GEM ssl signature anymore.
