### ISSUE TITLE
Cert file has expired

### ISSUE THREAD

**Issue by scottlowe** [thesp0nge/dawnscanner#138]
Following instructions in the README, does not result in an installed Dawn gem. This is the result:

    scott$ gem install dawnscanner -P MediumSecurity
    ERROR:  While executing gem ... (Gem::Security::Exception)
        certificate /CN=austin/DC=rubyforge/DC=org not valid after 2014-02-04 03:33:27 UTC

I suspect that most people go on to install from source as I have, which could be why you're not alerted to this issue.

**Comment by thesp0nge** [comment]
Hi Scott, unfortunately this is a certificate for a dependency gem. I can't renew this certificate

**Comment by scottlowe** [comment]
Ahh... apologies for the misdirected issue, then :blush:
