### ISSUE TITLE
The "development" branch is missing

### ISSUE THREAD

**Issue by olistik** [thesp0nge/dawnscanner#167]
As per https://github.com/thesp0nge/dawnscanner#contribute-to-dawnscanner the repository should provide a `development` branch.

**Comment by thesp0nge** [comment]
Sure. When the 1-5-0 branch will be merged back in master, than we fork into 'development' and 'master' to reflect major release development roadmap

**Comment by olistik** [comment]
@thesp0nge cool :-) Can I start forking `1-5-0` in the meanwhile?

**Comment by olistik** [comment]
@thesp0nge 1.5.0 is already been merged [link](https://github.com/thesp0nge/dawnscanner/commit/24e3b7e39a774a894c6700a85b63c4b1a76de29a) :-)
Could you branch out master into development?

**Comment by thesp0nge** [comment]
Not yet. There is already the v1-5-5 branch that it will be the January release and *then* we will use master/development branching model.

**Comment by thesp0nge** [comment]
Fixed. Now branch v1-5-5 is the development branch :-)
