### ISSUE TITLE
ERROR:  While executing gem ... (Gem::Security::Exception)

### ISSUE THREAD

**Issue by cjbischoff** [thesp0nge/dawnscanner#178]
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=paolo/DC=codesake/DC=com not valid after 2015-01-27 17:25:01 UTC
- Warning from the install:
  The bcrypt-ruby gem has changed its name to just bcrypt.  Instead of
  installing `bcrypt-ruby`, you should install `bcrypt`.  Please update your
  dependencies accordingly

Doesn't installed after the addition of the certificate and it has expired

❯❯❯ gem cert --list                                                                                                                                                                                  ⏎ (git:master)
/CN=paolo/DC=dawnscanner/DC=org

I am missing something?

**Comment by thesp0nge** [comment]
This is odd. This is an error fixed last year (or it was supposed to). Can you please tell me the exact gem install command are you issuing ?

**Comment by cjbischoff** [comment]
christopher@PhishMe λ ~ rb:ruby-2.1.6 node:system py:py27
❯❯❯ gem cert --list
/CN=paolo/DC=dawnscanner/DC=org

christopher@PhishMe λ ~ rb:ruby-2.1.6 node:system py:py27
❯❯❯ ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]

christopher@PhishMe λ ~ rb:ruby-2.1.6 node:system py:py27
❯❯❯ gem install dawnscanner -P MediumSecurity
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=paolo/DC=codesake/DC=com not valid after 2015-01-27 17:25:01 UTC

christopher@PhishMe λ ~ rb:ruby-2.1.6 node:system py:py27
❯❯❯ gem install dawnscanner --pre -P MediumSecurity                                                                                                                                                              ⏎
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=paolo/DC=codesake/DC=com not valid after 2015-01-27 17:25:01 UTC

christopher@PhishMe λ ~ rb:ruby-2.1.6 node:system py:py27

**Comment by twmills** [comment]
I am seeing the same problem.

**Comment by nicolasmery** [comment]
Same here

**Comment by phspies** [comment]
Just tried installing this gem and getting the same error:

certificate /CN=paolo/DC=codesake/DC=com not valid after 2015-01-27 17:25:01 UTC

**Comment by thesp0nge** [comment]
Guys @twmills @nicolasmery @phspies ... can you share more details about the error. I need to know details about your env (ruby version, gem version, os)

**Comment by phspies** [comment]
Ubuntu 15.04

ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

gem list

*** LOCAL GEMS ***

actionmailer (4.2.5.1, 4.2.5, 4.2.4)
actionpack (4.2.5.1, 4.2.5, 4.2.4)
actionview (4.2.5.1, 4.2.5, 4.2.4)
activejob (4.2.5.1, 4.2.5, 4.2.4)
activemodel (4.2.5.1, 4.2.5, 4.2.4)
activerecord (4.2.5.1, 4.2.5, 4.2.4)
activesupport (4.2.5.1, 4.2.5, 4.2.4)
acts_as_list (0.7.2)
acts_as_tree (2.4.0, 2.3.0)
addressable (2.4.0)
ajax_pagination (0.6.3)
ansi (1.5.0)
arel (6.0.3)
audited (4.2.1)
audited-activerecord (4.2.1)
bcrypt (3.1.10)
bcrypt-ruby (3.1.5)
bigdecimal (1.2.6)
builder (3.2.2)
bundler (1.10.6)
bundler-unload (1.0.2)
chef (12.6.0)
chef-config (12.6.0)
chef-zero (4.5.0)
chronic (0.10.2)
coderay (1.1.0)
coffee-rails (4.1.1, 4.1.0)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
colorize (0.7.7)
concurrent-ruby (1.0.0)
connection_pool (2.2.0)
cvss (0.99.0)
daemons (1.2.3)
data_mapper (1.2.0)
data_objects (0.10.17)
deep_cloneable (2.2.0, 2.1.1)
devise (3.5.6, 3.5.3, 3.5.2)
diff-lcs (1.2.5)
dimensiondata (2.0.0)
dm-aggregates (1.2.0)
dm-constraints (1.2.0)
dm-core (1.2.1)
dm-do-adapter (1.2.0)
dm-migrations (1.2.0)
dm-serializer (1.2.2)
dm-sqlite-adapter (1.2.0)
dm-timestamps (1.2.0)
dm-transactions (1.2.0)
dm-types (1.2.2)
dm-validations (1.2.0)
do_sqlite3 (0.10.17)
erubis (2.7.0)
ethon (0.8.1)
eventmachine (1.0.9.1, 1.0.8)
execjs (2.6.0)
executable-hooks (1.3.2)
fastercsv (1.5.5)
ffi (1.9.10)
ffi-yajl (2.2.3)
gem-wrappers (1.2.7)
globalid (0.3.6)
gssapi (1.2.0)
gyoku (1.3.1)
haml (4.0.7)
hashie (3.4.3)
highline (1.7.8)
hike (1.2.3)
httpclient (2.7.1)
i18n (0.7.0)
io-console (0.4.3)
ipaddress (0.8.2)
jbuilder (2.4.1, 2.4.0, 2.3.2)
jquery-historyjs (0.3.0)
jquery-popover (1.1.0)
jquery-rails (4.1.0, 4.0.5)
jquery-ui-rails (4.0.5)
jquery-validation-rails (1.13.1)
json (1.8.3, 1.8.1)
json_pure (1.8.3)
knife-dimensiondata (2.0.1)
knife-windows (1.2.0)
libv8 (3.16.14.13 x86_64-linux)
libyajl2 (1.2.0)
little-plugger (1.1.4)
logging (2.0.0)
loofah (2.0.3)
mail (2.6.3)
method_source (0.8.2)
mime-types (2.99.1, 2.99)
mini_portile2 (2.0.0)
minitest (5.8.4, 5.8.3, 5.4.3)
mixlib-authentication (1.4.0)
mixlib-cli (1.5.0)
mixlib-config (2.2.1)
mixlib-log (1.6.0)
mixlib-shellout (2.2.6)
multi_json (1.11.2)
mysql2 (0.3.20)
net-scp (1.2.1)
net-ssh (2.9.4)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.1)
net-telnet (0.1.1)
netaddr (1.5.1)
nokogiri (1.6.7.2, 1.6.7.1, 1.6.7)
nori (2.6.0)
ohai (8.10.0)
oj (2.14.6)
orm_adapter (0.5.0)
paper_trail (4.1.0)
papertrail (0.9.15)
passenger (5.0.22)
plist (3.1.0)
power_assert (0.2.2)
proxifier (1.0.3)
pry (0.10.3)
psych (2.0.8)
rabl (0.12.0, 0.11.7, 0.11.6)
rack (1.6.4)
rack-test (0.6.3)
rails (4.2.5.1, 4.2.5, 4.2.4)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3, 1.0.2)
rails-observers (0.1.2)
railties (4.2.5.1, 4.2.5, 4.2.4)
rake (10.5.0, 10.4.2)
rdoc (4.2.0)
redis (3.2.2)
ref (2.0.0)
request_store (1.3.0)
responders (2.1.1, 2.1.0)
rspec (3.4.0)
rspec-core (3.4.2)
rspec-expectations (3.4.0)
rspec-its (1.2.0)
rspec-mocks (3.4.1)
rspec-support (3.4.1)
rspec_junit_formatter (0.2.3)
rubygems-bundler (1.4.4)
rubyntlm (0.5.3)
rvm (1.11.3.9)
sass (3.2.19)
sass-rails (4.0.5)
serverspec (2.29.1)
sfl (2.2)
sidekiq (4.1.0, 4.0.1)
slop (3.6.0)
specinfra (2.50.4)
sprockets (2.12.4)
sprockets-rails (2.3.3)
stringex (1.5.1)
syslog-logger (1.6.8)
systemu (2.6.5)
test-unit (3.0.8)
therubyracer (0.12.2)
thin (1.6.4)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
time_diff (0.3.0)
timeout (0.0.1)
timeout-extensions (0.0.0)
turbolinks (2.5.3)
typhoeus (1.0.1)
tzinfo (1.2.2)
uglifier (2.7.2)
uuidtools (2.1.5)
warden (1.2.6, 1.2.4, 1.2.3)
will_paginate (3.1.0, 3.0.7)
winrm (1.6.0)
wmi-lite (1.0.0)
xml-simple (1.1.5)

**Comment by jussiauvinen** [comment]
Hi,

I have the same problem. I am running Ruby in a docker container, called ruby. 

After installing the cert for , I get installation error:


I haven't done anything to the container but trying to install the dawnscanner. 

Jussi

**Comment by yurijmi** [comment]
@jussiauvinen running without ``` -P MediumSecurity``` fixed it for me.

**Comment by martinstreicher** [comment]
I get this...

```
Colossus:prompt strike$ gem install dawnscanner -P MediumSecurity
Fetching: cvss-0.99.0.gem (100%)
WARNING:  cvss-0.99.0 is not signed
Successfully installed cvss-0.99.0
Fetching: sys-uname-1.0.3.gem (100%)
ERROR:  While executing gem ... (Gem::Security::Exception)
    root cert /CN=djberg96/DC=gmail/DC=com is not trusted
```

**Comment by IgorPolyakov** [comment]
@martinstreicher  try run command with `sudo`

**Comment by IgorPolyakov** [comment]
Same problem
```
sudo gem install dawnscanner --pre -P MediumSecurity
...
certificate /CN=ryand-ruby/DC=zenspider/DC=com not valid after 2017-09-26
```
