### ISSUE TITLE
root cert /CN=djberg96/DC=gmail/DC=com is not trusted

### ISSUE THREAD

**Issue by fauno** [thesp0nge/dawnscanner#195]
as per the instructions, i've installed the '/CN=paolo/DC=dawnscanner/DC=org' certificate, but installing the gem throws the error on the title :)

**Comment by thesp0nge** [comment]
Because you get another certificate "djberg96@gmail.com" that is not trusted... add also this one

**Comment by fauno** [comment]
which one?

**Comment by thesp0nge** [comment]
The one you reported in the issue as title...

**Comment by fauno** [comment]
i mean where should i get it and why should i trust it? :D

**Comment by thesp0nge** [comment]
I'm confused. You opened an issue for an untrusted certificate I don't own.

**Comment by fauno** [comment]
yes!  isn't that worrying?  i followed the instructions on the readme: 1) add the certificate; 2) install the gem.  but then the gem is signed by another entity!

i just retried the gem install and it worked, but no idea if it's because the gem isn't signed anymore :|

**Comment by thesp0nge** [comment]
You're missing a point. djberg96@gmail.com certificate, is used to sign one of the dawnscanner, dependencies... 

Dawnscanner gem is not signed by another entity!
A bit of google can clarify with this post: https://github.com/sensu-plugins/sensu-plugins-disk-checks/issues/24

**Comment by fauno** [comment]
:)
