### ISSUE TITLE
Configurable results folder

### ISSUE THREAD

**Issue by baburdick** [thesp0nge/dawnscanner#198]
It would be useful to be able to configure dawnscanner to save the results to the target repo folder (e.g. Rails.root) at a stable path so that results can be checked in to the target repo itself.

I don't see it in the documentation. And changing output to a file path in dawnscanner.yml doesn't make this happen. And running `dawn -F my_output.txt .` doesn't generate a file.

Is this not possible?

**Comment by thesp0nge** [comment]
Hi @baburdick in order for dawnscanner to use a custom file as output, you have to use also the -K flag, specifying you don't want tabular output but plain ascii instead.

At the moment dawnscanner uses $HOME/dawnscanner/results as root dir to store results. If you need to move in your report folder, maybe you have to concatenate dawnscanner with a shell mv command.
