### ISSUE TITLE
Error when gem cert --add <(curl -Ls https://raw.githubusercontent.com/thesp0nge/dawnscanner/master/certs/paolo_at_dawnscanner_dot_org.pem) on Windows

### ISSUE THREAD

**Issue by MarcioPorto** [thesp0nge/dawnscanner#200]
I have try running the command "gem cert --add <(curl -Ls https://raw.githubusercontent.com/thesp0nge/dawnscanner/master/certs/paolo_at_dawnscanner_dot_org.pem)" on Windows but it never seems to work. I keep getting the "The system cannot find the file specified" error.

**Comment by thesp0nge** [comment]
Hi Marcio, I'm really sorry but the file is in place... on Windows, you don't have curl command. You must download the cert manually, and then add with gem cert --add.

Please note that Windows is not officially supported by dawnscanner.
