### ISSUE TITLE
Issue while running dawn on Windows 7 64 bit: invalid port number in uri.rb

### ISSUE THREAD

**Issue by earthling1984** [thesp0nge/dawnscanner#203]
When I run my first dawn scan on windows, I get the following error:

D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:
1335:in `port=': Invalid port number: "\\Users\\<username>\\dawnscanne
r\\db\\dawnscanner.db" (Addressable::URI::InvalidURIError)
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addres
sable/uri.rb:800:in `block in initialize'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addres
sable/uri.rb:2302:in `call'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addres
sable/uri.rb:2302:in `defer_validation'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addres
sable/uri.rb:792:in `initialize'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addres
sable/uri.rb:135:in `new'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addres
sable/uri.rb:135:in `parse'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/ad
apters.rb:115:in `normalize_options_string'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/ad
apters.rb:63:in `normalize_options'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/ad
apters.rb:12:in `new'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core.rb
:230:in `setup'
        from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dawnscanner-1.6.2/bin/dawn:1
6:in `<top (required)>'
        from D:/Ruby22-x64/bin/dawn:22:in `load'
        from D:/Ruby22-x64/bin/dawn:22:in `<main>'

Please help in resolving this

**Comment by thesp0nge** [comment]
I'm really sorry but playing with Ruby on Windows is a big mess and at the moment I don't want to spend time in supporting Windows and friends.

I can suggest you creating a very basic virtual machine with any flavour of Linux and do your ruby code review from there.
