### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by thesp0nge** [thesp0nge/dawnscanner#204]
http://dawnscanner.org is down at the moment

**Comment by jasnow** [comment]
Still down.

**Comment by thesp0nge** [comment]
Up now!

**Comment by thesp0nge** [comment]
With SSL provided by letsencrypt

**Comment by jasnow** [comment]
Now I get "Welcome to nginx!"

**Comment by thesp0nge** [comment]
Strange... http://dawnscanner.org will redirect to https://dawnscanner.org

**Comment by jasnow** [comment]
Now it is working. FYI

**Comment by shayneoAtNorwood** [comment]
Bump. Your certs kaput again.
