### ISSUE TITLE
Cert expired on 2/23/2017

### ISSUE THREAD

**Issue by jdimmerman** [thesp0nge/dawnscanner#224]
The certificate with key at https://raw.githubusercontent.com/thesp0nge/dawnscanner/master/certs/paolo_at_dawnscanner_dot_org.pem expired on 2/23/17.  Therefore, executing:

```
gem cert --add <(curl -Ls https://raw.githubusercontent.com/thesp0nge/dawnscanner/master/certs/paolo_at_dawnscanner_dot_org.pem)
gem install dawnscanner -P MediumSecurity
```

results in

```
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=paolo/DC=dawnscanner/DC=org not valid after 2017-02-23 09:20:32 UTC
```

**Comment by ktec** [comment]
Is there any way around this?

**Comment by thesp0nge** [comment]
release v 1.6.8 with new signature

**Comment by jdimmerman** [comment]
@ktec you can also just gem install `dawnscanner` without `-P MediumSecurity`
