### ISSUE TITLE
certificate expired while gem installing

### ISSUE THREAD

**Issue by zyong812** [thesp0nge/dawnscanner#228]
When I install this gem by running `gem install dawnscanner -P MediumSecurity`, it prompts as follows: 
```
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=ryand-ruby/DC=zenspider/DC=com not valid after 2017-09-26 01:57:35 UTC
```

It seems the certificate is expired. Could you please update the certificate?

**Comment by thesp0nge** [comment]
Hi @zyong812 unfortunately it's a certificate for a third party library

**Comment by thesp0nge** [comment]
Minitest I suspect

**Comment by zyong812** [comment]
thanks anyway @thesp0nge
