### ISSUE TITLE
Fix hardcoded knowledge base path

### ISSUE THREAD

**Issue by tmaier** [thesp0nge/dawnscanner#244]
I wanted to try out the latest RC in order to understand if #230 has been resolved.

Unfortunately, the test failed, as the knowledge base has not been found.

The reason seems to be that the knowledgebase path is hardcoded to `/home/thesp0nge/src/hacking/dawnscanner/db`.

References
* https://github.com/thesp0nge/dawnscanner/blob/kb_revamp_in_yaml/lib/dawn/cli/dawn_cli.rb#L20
* https://github.com/thesp0nge/dawnscanner/blob/kb_revamp_in_yaml/lib/dawn/engine.rb#L177

I am also not sure if the necessary data exist at `https://dawnscanner.org/data/`

**Comment by thesp0nge** [comment]
Sorry for being so late :)
