### ISSUE TITLE
Cannot run dawnscanner against the src code of a ruby applcation

### ISSUE THREAD

**Issue by Allevon412** [thesp0nge/dawnscanner#246]
dawn -V ~/Desktop/transcoder-worker/src
I, [2020-06-22 14:54:59#5953]  INFO -- : dawn v1.6.9 is starting up
E, [2020-06-22 14:54:59#5953] ERROR -- : nothing to do on Desktop/transcoder-worker/src

**Comment by vpereira** [comment]
AFAICS it "only" supports rails, padrino or sinatra applications https://github.com/thesp0nge/dawnscanner/blob/master/lib/dawn/core.rb#L92

**Comment by thesp0nge** [comment]
@Allevon412 you can check the dependencies for known issues with the -G flag specifying the Gemfile.lock path
