### ISSUE TITLE
File.exists is removed from ruby 3.2 (was deprecated in 2.7). 

### ISSUE THREAD

**Issue by dennistdk** [thesp0nge/dawnscanner#252]
> /bundle_cache/ruby/3.2.0/gems/dawnscanner-1.6.9/lib/dawn/kb/pattern_match_check.rb:64:in block in vuln?: undefined method exists? for File:Class (NoMethodError)
>
> matches = run(load_file(filename)) if File.exists?(filename) && File.file?(filename) && ! File.binary?(filename) && ! must_exclude?(filename)
>
> Did you mean?  exist?

**Comment by puzzler7** [comment]
+1, getting the exact same issue trying to run Dawnscanner on one of the example repos.
