### ISSUE TITLE
Security exception thrown when installing.

### ISSUE THREAD

**Issue by sdwolf** [thesp0nge/dawnscanner#99]
When executing this command:
```
gem install dawnscanner -P MediumSecurity
```
It gives:
```
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=austin/DC=rubyforge/DC=org not valid after 2014-02-04 03:33:27 UTC
```

**Comment by thesp0nge** [comment]
Hi @sdwolf this is a security exception for a third party gem, since I don't own austin.rubyforge.org... I'll double check dependencies...

**Comment by thesp0nge** [comment]
The problem is mime-types gem (https://gist.github.com/steakknife/5334145)
